### ISSUE TITLE
error in installation, I can't use it!

### ISSUE THREAD

**Issue by vassilaros** [opengisch/qgis_trackable_project_files#4] opened 2019-04-12 13:06 UTC
I installed the extension, but sent me the following error

```
Couldn't load plugin 'trackable_project_files' 

ModuleNotFoundError: No module named 'lxml' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Vassilis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\trackable_project_files\__init__.py", line 13, in 
    import lxml.etree as ET
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'lxml'


Python Έκδοση: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Έκδοση Qgis: 3.6.1-Noosa Noosa, 2468226bc9 

Python Path:
C:/Users/Vassilis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\LAStools
C:/Users/Vassilis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\gml_application_schema_toolbox\extlibs
C:/OSGEO4~1/apps/qgis/./python
C:/Users/Vassilis/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Vassilis/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/Vassilis/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Vassilis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\Vassilis\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\shapetools\ext-libs
```

**Comment by mstuyts** [comment] 2019-04-12 13:52
This is the same problem as issue #1.

**Comment by mbernasocchi** [comment] 2019-04-23 13:24
closing as duplicate of #1

**Closed as completed by mbernasocchi** 2019-04-23 13:24 UTC
