### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'lxml'


### ISSUE THREAD

**Issue by willyqgis** [opengisch/qgis_trackable_project_files#13] opened 2019-11-01 01:49 UTC
No se pudo cargar el complemento 'trackable_project_files'
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/HP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\trackable_project_files\__init__.py", line 13, in <module>
    import lxml.etree as ET
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis-ltr/./python\qgis\utils.py", line 685, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'lxml'

```
trackable_project_files 1.2.0, QGIS 3.4.13-Madeira on Windows 10

**Comment by m-kuhn** [comment] 2019-11-01 07:53
Duplicate of #1 
There is a workaround documented in there too.

**Closed as completed by m-kuhn** 2019-11-01 07:53 UTC
